DROP TABLE IF EXISTS HISTORY;
DROP TABLE IF EXISTS SECURITIES;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE SECURITIES
(
    id               INTEGER    GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    sec_id           VARCHAR(36)             NOT NULL UNIQUE,
    reg_number       VARCHAR(189)            ,
    name             VARCHAR(765)            NOT NULL,
    emitent_title    VARCHAR(765)            NOT NULL
);

CREATE TABLE HISTORY
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    sec_id      INTEGER                      NOT NULL,
    trade_date  DATE                         NOT NULL,
    num_trades  double                       ,
    open        double                       ,
    close       double                       ,
    FOREIGN KEY (sec_id) REFERENCES securities(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX history_unique_secid_tradedate_numtrade_idx ON HISTORY(sec_id,trade_date,num_trades)



